sudo: required
language: python
services:
        - docker

script:
        - docker build -t koora:v1 .
        - docker tag koora:v1  registry.heroku.com/pure-meadow-08274/web
        - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
        - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  
          
deploy:   
        provider: script
        script:
               docker push registry.heroku.com/pure-meadow-08274/web
               heroku container:release web --app pure-meadow-08274
        on:
          branch: aabhusan
