sudo: required
language: python
services:
        - docker

script:
        - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
        - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  
          
deploy:   
        provider: script
        script:
               heroku container:push web 
               heroku container:release web --app pure-meadow-08274
        on:
          branch: aabhusan
